name: Default workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ matrix.node-version }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-${{ matrix.node-version }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-${{ matrix.node-version }}-build-
            ${{ runner.OS }}-${{ matrix.node-version }}-
            ${{ runner.OS }}-

      - run: yarn install
      - run: yarn lint

  commit-watch:
    runs-on: ubuntu-latest
    if: contains(github.event_name, 'pull_request')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: npx @eqworks/commit-watch -b ${{ github.event.pull_request.base.sha }} -h ${{ github.event.pull_request.head.sha }} -v

  depcheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npx depcheck

  release:
    name: Trigger a release
    runs-on: ubuntu-latest
    needs: [lint, depcheck]
    if: contains(github.event_name, 'push')
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install
      - name: Create tag
        if: ${{ success() }}
        run: node index.js tag --github -v
        env:
          GITHUB_OWNER: EQWorks
          GITHUB_TOKEN: ${{ secrets.CD_GITHUB_TOKEN }}
